name: release

on:
  push:
    tags:
      - "v*"

jobs:
  createrelease:
    name: create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: true
      - run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt
      - uses: actions/upload-artifact@v1
        with:
          name: release_url
          path: release_url.txt

  macos:
    needs: [createrelease]
    name: build and upload
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
              os: ubuntu-latest,
              suffix: "x86-amd64.deb",
              asset_path: "./target/release/radical-native.deb",
            }
          - {
              os: ubuntu-latest,
              suffix: "x86-amd64",
              asset_path: "./target/release/radical-native",
            }
          - {
              os: macos-latest,
              suffix: "darwin.pkg",
              asset_path: "./target/release/radical-native.pkg",
            }
          - {
              os: windows-latest,
              suffix: "win64.exe",
              asset_path: "./target/release/radical-native-installer.exe",
            }
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: release_url

      - name: prereq
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          sudo apt-get install libsqlcipher0 libsqlcipher-dev
          cargo install cargo-deb

      - name: build
        id: build
        shell: bash
        run: |
          npm install
          npm run lint
          npm run build:native

          value=`cat release_url/release_url.txt`
          echo "::set-output name=upload_url::$value"
          echo "::set-output name=version::${GITHUB_REF:10}"

      - id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.build.outputs.upload_url }}
          asset_path: ${{ matrix.config.asset_path }}
          asset_name: radical-native_${{ steps.build.outputs.version }}_${{ matrix.config.suffix }}
          asset_content_type: application/octet-stream
